<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="obj\**" />
    <Compile Remove="ABCRetail.Tests\**" />
    <Compile Remove="ABCRetail.Functions\**" />
    <Compile Remove="SortApplication\**" />
    <Compile Remove="publish\**" />
    <Content Remove="bin\**" />
    <Content Remove="obj\**" />
    <Content Remove="ABCRetail.Tests\**" />
    <Content Remove="ABCRetail.Functions\**" />
    <Content Remove="SortApplication\**" />
    <Content Remove="publish\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="obj\**" />
    <EmbeddedResource Remove="ABCRetail.Tests\**" />
    <EmbeddedResource Remove="ABCRetail.Functions\**" />
    <EmbeddedResource Remove="SortApplication\**" />
    <EmbeddedResource Remove="publish\**" />
    <None Remove="bin\**" />
    <None Remove="obj\**" />
    <None Remove="ABCRetail.Tests\**" />
    <None Remove="ABCRetail.Functions\**" />
    <None Remove="SortApplication\**" />
    <None Remove="publish\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.27.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.27.1" />
  </ItemGroup>

</Project>
